site_name: MkDocs Merge
site_description: MkDocs site merge tool
site_author: Oscar Vasquez
site_url: https://ovasquez.github.io/mkdocs-merge/

copyright: 'Copyright &copy; Oscar Vasquez'

repo_name: 'ovasquez/mkdocs-merge'
repo_url: 'https://github.com/ovasquez/mkdocs-merge'


nav:
  - Home: index.md
  - Changelog: changelog.md

theme:
  name: material
  palette:
     # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: material/source-repository-multiple

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true