# File: .github/workflows/deploy-mkdocs.yml
name: Deploy MkDocs Site

on:
  workflow_dispatch:
  push:
    paths:
        - 'docs/**'
        - 'mkdocs.yml'

# Grant permissions needed by the Pages actions
permissions:
  contents: read           # for checkout
  pages: write             # to publish
  id-token: write          # for authentication with deploy-pages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install MkDocs + MkDocs Material
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material 

      # 4) Build the site into a folder named `site/`
      - name: Build MkDocs site
        run: mkdocs build --site-dir site

      # 5) Upload the generated site to GitHub Pages
      #    This uses the new official Pages actions:
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1