# File: .github/workflows/docs-publish.yml
name: Publish MkDocs-Merge Documentation

on:
  workflow_dispatch:
  push:
    paths:
        - 'docs/**'
        - 'mkdocs.yml'

# Grant permissions needed by the Pages actions
permissions:
  contents: read           # for checkout
  pages: write             # to publish
  id-token: write          # for authentication with deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3) Install MkDocs + MkDocs Material
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material 

      # 4) Build the site into a folder named `site/`
      - name: Build MkDocs site
        run: mkdocs build --site-dir site

      # 5) Upload the generated site to GitHub Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4